package tools.vitruv.methodologist.vsum.controller.dto.response;

import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Response DTO representing a snapshot of a VSUM history entry.
 *
 * <p>This DTO contains the minimal fields required by API clients when listing or retrieving VSUM
 * history entries. Accessors and constructors are generated by Lombok.
 */
@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class VsumHistoryResponse {
  private Long id;
  private Instant createdAt;
}
