CREATE TABLE vsum_invitation
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_id       BIGINT                                  NOT NULL,
    invited_by    BIGINT,
    invitee_email VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    accepted_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsum_invitation PRIMARY KEY (id)
);

CREATE INDEX idx_vsum_invitation_invitee_email ON vsum_invitation (invitee_email);
CREATE INDEX idx_vsum_invitation_vsum_id ON vsum_invitation (vsum_id);