CREATE TABLE constraint_rule_set
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_id        BIGINT                                  NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    color          VARCHAR(50)                             NOT NULL DEFAULT '#3b82f6',
    description    TEXT,
    file_storage_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_constraint_rule_set PRIMARY KEY (id)
);

ALTER TABLE constraint_rule_set
    ADD CONSTRAINT FK_CONSTRAINT_RULE_SET_ON_VSUM FOREIGN KEY (vsum_id) REFERENCES vsum (id) ON DELETE CASCADE;

ALTER TABLE constraint_rule_set
    ADD CONSTRAINT FK_CONSTRAINT_RULE_SET_ON_FILE_STORAGE FOREIGN KEY (file_storage_id) REFERENCES file_storage (id);

CREATE INDEX idx_constraint_rule_set_vsum_id ON constraint_rule_set (vsum_id);
