CREATE TABLE vsum_build
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_id         BIGINT                                  NOT NULL,
    requested_by_id BIGINT                                  NOT NULL,
    fingerprint     VARCHAR(64)                             NOT NULL,
    status          VARCHAR(32)                             NOT NULL,
    forced          BOOLEAN                                 NOT NULL DEFAULT FALSE,
    error_message   TEXT,
    artifact_id     BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    started_at      TIMESTAMP WITHOUT TIME ZONE,
    finished_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsumbuild PRIMARY KEY (id)
);

ALTER TABLE vsum_build
    ADD CONSTRAINT FK_VSUMBUILD_ON_VSUM FOREIGN KEY (vsum_id) REFERENCES vsum (id);

ALTER TABLE vsum_build
    ADD CONSTRAINT FK_VSUMBUILD_ON_REQUESTED_BY FOREIGN KEY (requested_by_id) REFERENCES usr (id);

ALTER TABLE vsum_build
    ADD CONSTRAINT FK_VSUMBUILD_ON_ARTIFACT FOREIGN KEY (artifact_id) REFERENCES file_storage (id);

CREATE INDEX idx_vsum_build_vsum_id_created_at ON vsum_build (vsum_id, created_at DESC);

CREATE INDEX idx_vsum_build_vsum_id_fingerprint_status ON vsum_build (vsum_id, fingerprint, status);
