CREATE TABLE file_storage
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename     VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    content_type VARCHAR(255)                            NOT NULL,
    size_bytes   BIGINT                                  NOT NULL,
    sha256       VARCHAR(255)                            NOT NULL,
    data         OID                                     NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_filestorage PRIMARY KEY (id)
);

CREATE TABLE meta_model
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    domain            VARCHAR(255)                            NOT NULL,
    keyword           TEXT[]                                  NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    ecore_file_id     BIGINT                                  NOT NULL,
    gen_model_file_id BIGINT                                  NOT NULL,
    is_clone          BOOLEAN                                 NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    removed_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_metamodel PRIMARY KEY (id)
);

CREATE TABLE usr
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    role_type  VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    removed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usr PRIMARY KEY (id)
);

CREATE TABLE versioning
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name     VARCHAR(255)                            NOT NULL,
    version      VARCHAR(255)                            NOT NULL,
    force_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_versioning PRIMARY KEY (id)
);

CREATE TABLE vsum
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    removed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsum PRIMARY KEY (id)
);

ALTER TABLE file_storage
    ADD CONSTRAINT FK_FILESTORAGE_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);

ALTER TABLE meta_model
    ADD CONSTRAINT FK_METAMODEL_ON_ECORE_FILE FOREIGN KEY (ecore_file_id) REFERENCES file_storage (id);

ALTER TABLE meta_model
    ADD CONSTRAINT FK_METAMODEL_ON_GEN_MODEL_FILE FOREIGN KEY (gen_model_file_id) REFERENCES file_storage (id);

ALTER TABLE meta_model
    ADD CONSTRAINT FK_METAMODEL_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);