CREATE TABLE vsum_meta_model
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_id       BIGINT                                  NOT NULL,
    meta_model_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    removed_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsummetamodel PRIMARY KEY (id)
);

ALTER TABLE meta_model
    ADD source_id BIGINT;

ALTER TABLE vsum
    ADD user_id BIGINT;

ALTER TABLE vsum
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE meta_model
    ADD CONSTRAINT FK_METAMODEL_ON_SOURCE FOREIGN KEY (source_id) REFERENCES meta_model (id);

ALTER TABLE vsum_meta_model
    ADD CONSTRAINT FK_VSUMMETAMODEL_ON_META_MODEL FOREIGN KEY (meta_model_id) REFERENCES meta_model (id);

ALTER TABLE vsum_meta_model
    ADD CONSTRAINT FK_VSUMMETAMODEL_ON_VSUM FOREIGN KEY (vsum_id) REFERENCES vsum (id);

ALTER TABLE vsum
    ADD CONSTRAINT FK_VSUM_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);

ALTER TABLE meta_model
DROP
COLUMN is_clone;