CREATE TABLE vsum_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsumuser PRIMARY KEY (id)
);

ALTER TABLE vsum_user
    ADD CONSTRAINT FK_VSUMUSER_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);

ALTER TABLE vsum_user
    ADD CONSTRAINT FK_VSUMUSER_ON_VSUM FOREIGN KEY (vsum_id) REFERENCES vsum (id);