CREATE TABLE meta_model_relation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_id          BIGINT                                  NOT NULL,
    source_id        BIGINT                                  NOT NULL,
    target_id        BIGINT                                  NOT NULL,
    reaction_file_id BIGINT                                  NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_metamodelrelation PRIMARY KEY (id)
);

ALTER TABLE meta_model_relation
    ADD CONSTRAINT FK_METAMODELRELATION_ON_REACTION_FILE FOREIGN KEY (reaction_file_id) REFERENCES file_storage (id);

ALTER TABLE meta_model_relation
    ADD CONSTRAINT FK_METAMODELRELATION_ON_SOURCE FOREIGN KEY (source_id) REFERENCES meta_model (id);

ALTER TABLE meta_model_relation
    ADD CONSTRAINT FK_METAMODELRELATION_ON_TARGET FOREIGN KEY (target_id) REFERENCES meta_model (id);

ALTER TABLE meta_model_relation
    ADD CONSTRAINT FK_METAMODELRELATION_ON_VSUM FOREIGN KEY (vsum_id) REFERENCES vsum (id);