CREATE TABLE vsum_history
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    creator_id     BIGINT                                  NOT NULL,
    vsum_id        BIGINT                                  NOT NULL,
    representation JSON,
    CONSTRAINT pk_vsumhistory PRIMARY KEY (id)
);

ALTER TABLE vsum_history
    ADD CONSTRAINT FK_VSUMHISTORY_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES usr (id);

ALTER TABLE vsum_history
    ADD CONSTRAINT FK_VSUMHISTORY_ON_VSUM FOREIGN KEY (vsum_id) REFERENCES vsum (id);