CREATE TABLE fine_granular_meta_model_relation
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meta_model_relation_id          BIGINT                                  NOT NULL,
    source_id                       VARCHAR(255)                            NOT NULL,
    target_id                       VARCHAR(255)                            NOT NULL,
    low_code_reaction_template      VARCHAR(255)                            NOT NULL,
    reaction_file_id                BIGINT                                  NOT NULL,
    created_at                      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_finegranularmetamodelrelation PRIMARY KEY (id)
);

ALTER TABLE fine_granular_meta_model_relation
    ADD CONSTRAINT uk_metamodelrelation_source_target_file UNIQUE (meta_model_relation_id, source_id, target_id, reaction_file_id);

ALTER TABLE fine_granular_meta_model_relation
    ADD CONSTRAINT FK_FINEGRANULARMETAMODELRELATION_ON_REACTION_FILE FOREIGN KEY (reaction_file_id) REFERENCES file_storage (id);

ALTER TABLE fine_granular_meta_model_relation
    ADD CONSTRAINT FK_FINEGRANULARMETAMODELRELATION_ON_VSUM FOREIGN KEY (meta_model_relation_id) REFERENCES meta_model_relation (id);