CREATE TABLE vsum_view
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_id         BIGINT                                  NOT NULL,
    file_storage_id BIGINT                                  NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsumview PRIMARY KEY (id)
);

CREATE TABLE vsum_view_meta_model
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vsum_view_id  BIGINT                                  NOT NULL,
    meta_model_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_vsumviewmetamodel PRIMARY KEY (id)
);

ALTER TABLE vsum_view_meta_model
    ADD CONSTRAINT FK_VSUMVIEWMETAMODEL_ON_META_MODEL FOREIGN KEY (meta_model_id) REFERENCES meta_model (id);

ALTER TABLE vsum_view_meta_model
    ADD CONSTRAINT FK_VSUMVIEWMETAMODEL_ON_VSUM_VIEW FOREIGN KEY (vsum_view_id) REFERENCES vsum_view (id);

ALTER TABLE vsum_view
    ADD CONSTRAINT FK_VSUMVIEW_ON_FILE_STORAGE FOREIGN KEY (file_storage_id) REFERENCES file_storage (id);

ALTER TABLE vsum_view
    ADD CONSTRAINT FK_VSUMVIEW_ON_VSUM FOREIGN KEY (vsum_id) REFERENCES vsum (id);