CREATE TABLE file_storage
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename     VARCHAR(255)                            NOT NULL,
    content_type VARCHAR(255)                            NOT NULL,
    size_bytes   BIGINT                                  NOT NULL,
    sha256       VARCHAR(255)                            NOT NULL,
    data         OID                                     NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_filestorage PRIMARY KEY (id)
);

CREATE TABLE meta_model
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    file_storage_id BIGINT                                  NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    removed_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_metamodel PRIMARY KEY (id)
);

CREATE TABLE usr
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    role_type  VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    removed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usr PRIMARY KEY (id)
);

CREATE TABLE versioning
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name     VARCHAR(255)                            NOT NULL,
    version      VARCHAR(255)                            NOT NULL,
    force_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_versioning PRIMARY KEY (id)
);

CREATE TABLE vsum
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    removed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsum PRIMARY KEY (id)
);

ALTER TABLE meta_model
    ADD CONSTRAINT uc_metamodel_file_storage UNIQUE (file_storage_id);

ALTER TABLE file_storage
    ADD CONSTRAINT FK_FILESTORAGE_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);

ALTER TABLE meta_model
    ADD CONSTRAINT FK_METAMODEL_ON_FILE_STORAGE FOREIGN KEY (file_storage_id) REFERENCES file_storage (id);

ALTER TABLE meta_model
    ADD CONSTRAINT FK_METAMODEL_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);