CREATE TABLE usr
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    role_type  VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    removed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usr PRIMARY KEY (id)
);

CREATE TABLE versioning
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name     VARCHAR(255)                            NOT NULL,
    version      VARCHAR(255)                            NOT NULL,
    force_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_versioning PRIMARY KEY (id)
);

CREATE TABLE vsum
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    removed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vsum PRIMARY KEY (id)
);